"""empty message

Revision ID: 4a32bcad2197
Revises: 
Create Date: 2026-04-10 17:22:06.654428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4a32bcad2197'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentmodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentmodel_doc_id'), ['doc_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentmodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentmodel_doc_id'))

    op.drop_table('documentmodel')
    # ### end Alembic commands ###
